export const CATEGORY_IMAGES = {
  smartphones: require("../assets/images/smartphones.jpg"),
  laptops: require("../assets/images/laptops.jpg"),
  fragrances: require("../assets/images/fragrances.jpg"),
  skincare: require("../assets/images/skincare.jpg"),
  groceries: require("../assets/images/groceries.jpg"),
  "home-decoration": require("../assets/images/home-decoration.jpg"),
  furniture: require("../assets/images/furniture.jpg"),
  tops: require("../assets/images/tops.jpg"),
  "womens-dresses": require("../assets/images/womens-dresses.jpg"),
  "womens-shoes": require("../assets/images/womens-shoes.jpg"),
  "mens-shirts": require("../assets/images/mens-shirts.jpg"),
  "mens-shoes": require("../assets/images/mens-shoes.jpg"),
  "mens-watches": require("../assets/images/mens-watches.jpg"),
  "womens-watches": require("../assets/images/womens-watches.jpg"),
  "womens-bags": require("../assets/images/womens-bags.jpg"),
  "womens-jewellery": require("../assets/images/womens-jewellery.jpg"),
  sunglasses: require("../assets/images/sunglasses.jpg"),
  automotive: require("../assets/images/automotive.jpg"),
  motorcycle: require("../assets/images/motorcycle.jpg"),
  lighting: require("../assets/images/lighting.jpg"),
} as const;
